### ISSUE TITLE
undefined symbol: ncclCommRegister

### ISSUE THREAD

**Issue by robotzheng** [microsoft/BitBLAS#39]
NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 12.3  
python 3.10.14
ubuntu 22.04

pip install typing_extensions-4.11.0-py3-none-any.whl
pip install bitblas-0.0.1.dev5-py3-none-manylinux1_x86_64.whl

python -c "import bitblas; print(bitblas.__version__)"  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/__init__.py", line 19, in <module>
    from . import gpu  # noqa: F401
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/gpu/__init__.py", line 7, in <module>
    from .fallback import Fallback  # noqa: F401
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/gpu/fallback.py", line 28, in <module>
    from ..base import normalize_prim_func, try_inline
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/base/__init__.py", line 16, in <module>
    from .transform import ApplyDefaultSchedule, ApplyFastTuning
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/base/transform.py", line 20, in <module>
    from .utils import fast_tune, fast_tune_with_dynamic_range
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/base/utils.py", line 22, in <module>
    from bitblas.utils import tensor_replace_dp4a, tensor_remove_make_int4
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/utils/__init__.py", line 4, in <module>
    from .tensor_adapter import tvm_tensor_to_torch, lazy_tvm_tensor_to_torch, lazy_torch_to_tvm_tensor  # noqa: F401
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/bitblas/utils/tensor_adapter.py", line 7, in <module>
    import torch
  File "/opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: /opt/conda/envs/EN_BITNET/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister

**Comment by xysmlx** [comment]
Hi, this error is from torch, which seems to be an environment problem. CUDA 12.x requires the driver version >= 525.60.13 ([cuda compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-11-and-later-defaults-to-minor-version-compatibility)). You may have a trial to upgrade the driver version.

If it still reports such problem, you can try to downgrade the torch version to 2.1.2 by ```pip install torch==2.1.2``` as suggested in [this issue](https://github.com/pytorch/pytorch/issues/119932#issuecomment-1946836805).

You can also try the docker image ```nvcr.io/nvidia/pytorch:23.01-py3```.

**Comment by LeiWang1999** [comment]
Closed as the question has been answered.
